# Etapa 1: Build do projeto com Maven
FROM maven:3.8.4-openjdk-11-slim AS build

# Defina o diretório de trabalho no contêiner
WORKDIR /chat

# Copie os arquivos do projeto para o contêiner
COPY . .

# Execute o comando Maven para compilar o projeto
RUN mvn clean install

# Etapa 2: Rodar o aplicativo com a imagem mais leve
FROM openjdk:11-jre-slim

# Defina o diretório de trabalho no contêiner
WORKDIR /chat

# Copie o arquivo JAR gerado pela primeira etapa
# O arquivo JAR está no diretório target/chat e seu nome será chat-0.0.1-SNAPSHOT.jar
COPY --from=build /chat/chat/target/chat-0.0.1-SNAPSHOT.jar /chat/chat.jar

# Comando para rodar o JAR
CMD ["java", "-jar", "/chat/chat.jar"]
